alias: tuin verlichting uit bij zonopgang
description: ""
mode: single
triggers:
  - event: sunrise
    offset: "-00:45:00"
    trigger: sun
  - at: "08:30:00"
    trigger: time
  - at: "01:00:00"
    trigger: time
conditions: []
actions:
  - action: scene.turn_on
    target:
      entity_id: scene.tuin_verlichting
    data: {}
